// Cartographie FL → SAP : les 151 champs du mapping (onglet « Mapping FL »
// de Mapping_champs_SAP.xlsx), classés par nature et statut de règle.
// Dérivé du fichier source — éditable à la main (notamment les statuts de règle).
// Sert la page d'aperçu `src/pages/FicheComplete.jsx`. Voir docs/mapping-fl.md.
//
// cat    : 'SAISIE' | 'CONSTANTE' | 'REGLE' | 'CALCUL' | 'WORKFLOW'
// status : 'saisie' | 'constante' | 'calcul' | 'workflow'
//          | 'regle_reusable' (base DE/DS réutilisable) | 'regle_todo' (à coder)

export const FL_FIELDS = [
  {
    "section": "En-tête fiche",
    "cellule": "D4",
    "lib": "Code article + VL",
    "sapField": "MARA-MATNR",
    "type": "Saisi (libre)",
    "valeur": "4198 + VL",
    "metier": "Tous les onglets",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "En-tête fiche",
    "cellule": "D5",
    "lib": "Branche",
    "sapField": "MARA-MBRSH",
    "type": "Liste déroulante",
    "valeur": "Agro Alimentaire",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "En-tête fiche",
    "cellule": "J3",
    "lib": "Définition",
    "sapField": "Notice interne",
    "type": "",
    "valeur": "",
    "metier": "Commerce/Définition du produit et date de mise à dispo",
    "rule": "La date de mise à disposition au format jj/mm/aa, suivie de \":\", puis : la définition produit 1 (ou vide si non renseignée) concaténée avec la définition produit 2 (ou vide si non renseignée)",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "En-tête fiche",
    "cellule": "D6",
    "lib": "Type article",
    "sapField": "MARA-MTART",
    "type": "Liste déroulante",
    "valeur": "3A-Produit Fini:PFINI",
    "metier": "Commerce/Fabrication ou négoce",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "En-tête fiche",
    "cellule": "D12",
    "lib": "Division WM",
    "sapField": "MBEW-WERKS",
    "type": "Liste déroulante",
    "valeur": "2847-Agen2",
    "metier": "Commerce/Origine fabrication",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "En-tête fiche",
    "cellule": "I12",
    "lib": "Division MM",
    "sapField": "MBEW-WERKS",
    "type": "Liste déroulante",
    "valeur": "2820-Olano Montauban",
    "metier": "Supply Chain/Sites de stockage",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "En-tête fiche",
    "cellule": "D13",
    "lib": "Magasin",
    "sapField": "MARD-LGORT",
    "type": "Saisi (libre)",
    "valeur": "95",
    "metier": "",
    "rule": "Si le groupe de marchandise commence par \"PF-H\" ET que la facturation est \"TDL\" : Si la marque commence par \"PIC\", \"THR\" ou \"DAV\" → valeur = \"95F\" Sinon, si la marque commence par \"CDP\" → valeur = \"95G\" Sinon → valeur = \"95\" Dans tous les autres cas → valeur = \"95\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "En-tête fiche",
    "cellule": "D14",
    "lib": "Org commerciale",
    "sapField": "MVKE-VKORG",
    "type": "Saisi (libre)",
    "valeur": "OC28",
    "metier": "Toujours OC28",
    "rule": "Si l'origine de fabrication commence par \"2834\" ou \"2866\" → valeur = \"OC37\" Sinon → valeur = \"OC28\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "ADV (en-tête)",
    "cellule": "D15",
    "lib": "Canal distrib (multi-valeurs)",
    "sapField": "MVKE-VTWEG",
    "type": "Liste déroulante",
    "valeur": "50-DEGAGEMENT | 99-TRANSFERT | 30-EXPORT | 70-RHF",
    "metier": "Commerce/Canaux de distribution",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "En-tête fiche",
    "cellule": "D16",
    "lib": "Numéro magasin",
    "sapField": "LGORT (MARD)",
    "type": "Saisi (libre)",
    "valeur": "847",
    "metier": "",
    "rule": "Si l'origine de fabrication (caractères 1 à 4) est : \"2802\" → \"802\" \"2833\" → \"833\" \"2847\" → \"847\" \"2886\" → \"886\" Sinon → vide",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D18",
    "lib": "Libellé Long FR",
    "sapField": "MAKT-MAKTX",
    "type": "Saisi (libre)",
    "valeur": "PLAQ COULEUR 4X5 EXPORT COREE",
    "metier": "Commerce/Libellé long FR 40",
    "rule": "Si libellé long volet 1 est vide → retourne une chaîne de 20 espaces Sinon → retourne libellé long volet 1 complété par des espaces jusqu'à 20 caractères, suivi de libellé long volet 2",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D19",
    "lib": "Libellé article normalisé",
    "sapField": "Z* (custom)",
    "type": "Saisi (libre)",
    "valeur": "PLAQ COULEUR 4X5 EXPORT COREE",
    "metier": "Commerce/Libellé Client",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D20",
    "lib": "Libellé article langue1-",
    "sapField": "MAKT-MAKTX (langue)",
    "type": "Liste déroulante",
    "valeur": "EXPORT KOREA",
    "metier": "Commerce/Code pays",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D21",
    "lib": "Libellé article langue2-",
    "sapField": "MAKT-MAKTX (langue)",
    "type": "Liste déroulante",
    "valeur": "*",
    "metier": "Commerce/Code pays",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D22",
    "lib": "Libellé article langue3-Z1-Libellé colis",
    "sapField": "MAKT + texte colis",
    "type": "Calculé (auto)",
    "valeur": "EXPORT PLAQUES 'TOUTES EN COULEURS'",
    "metier": "Industriel/Libellé produit sur l'étiquette colis",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D23",
    "lib": "Unité de qté base",
    "sapField": "MARA-MEINH",
    "type": "Saisi (libre)",
    "valeur": "U",
    "metier": "",
    "rule": "Toujours U ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "I23",
    "lib": "Grpe marchand",
    "sapField": "MARA-MATKL",
    "type": "Liste déroulante",
    "valeur": "PF-AS-MBSA- PFinis Agen Surgel",
    "metier": "Industriel/Eclatement groupe de marchandises",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D24",
    "lib": "Ancien n°article",
    "sapField": "MARA-BISMT",
    "type": "Saisi (libre)",
    "valeur": "6016",
    "metier": "Commerce/BIV",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D25",
    "lib": "Secteur d'activité",
    "sapField": "MARA-SPART",
    "type": "Liste déroulante",
    "valeur": "10-1°Mque RHF/Boulpat GMS",
    "metier": "Commerce/Secteur d'activité",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "I25",
    "lib": "Hiér produits Fam",
    "sapField": "MARA-PRDHA",
    "type": "Liste déroulante",
    "valeur": "27 M4 40 MH -TRAITEUR/PLAQUES DE PAIN/BASES CREATIVES/PLAQUES DE PAIN",
    "metier": "Commerce/Hiérarchie produit famille",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D26",
    "lib": "Groupe autorisations",
    "sapField": "MARA-BEGRU",
    "type": "Saisi (libre)",
    "valeur": "PFIN",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → vide Sinon → Les caractères 17 à 20 du type article.",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "D43",
    "lib": "Désign normalisée",
    "sapField": "Z* (custom)",
    "type": "Calculé (auto)",
    "valeur": "PLAQ COULEUR 4X5",
    "metier": "Commerce/Libellé article caisse",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "N43",
    "lib": "Document",
    "sapField": "ZEINR",
    "type": "Saisi (libre)",
    "valeur": "4709104",
    "metier": "",
    "rule": "Si l'origine (caractères 1 à 4) est : \"2802\" → \"1106901\" \"2886\" → \"64134100\" \"2847\" → \"4709104\" Sinon → vide",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "DONNÉES DE BASE",
    "cellule": "Q43",
    "lib": "Profil code MD",
    "sapField": "MARA-PROFL",
    "type": "Saisi (libre)",
    "valeur": "",
    "metier": "",
    "rule": "Si ProduitGirafe = 3 → \"GIR\" Si ProduitGirafe = 4 → \"PCH\" Sinon → vide Mais ProduitGirafe est toujours vide onglet saisie cellule ED Design categ de classe 023-LOBM VFDAT",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "ADV:Org.Comm.1",
    "cellule": "D46",
    "lib": "Unité de qté base",
    "sapField": "MARA-MEINS",
    "type": "Saisi (libre)",
    "valeur": "U",
    "metier": "",
    "rule": "Toujours U",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "ADV:Org.Comm.1",
    "cellule": "K46",
    "lib": "OC1-secteur d'activité",
    "sapField": "MARA-SPART",
    "type": "Liste déroulante",
    "valeur": "10-1°Mque RHF/Boulpat GMS",
    "metier": "Commerce/Secteur d'activité",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:Org.Comm.1",
    "cellule": "P46",
    "lib": "OC1-Unité Livraison",
    "sapField": "table (nombre entier) MVKE-SCMNG et MVKE-SCHME",
    "type": "Saisi (libre)",
    "valeur": "1 / ZCO",
    "metier": "table (nombre entier) MVKE-SCMNG et MVKE-SCHME",
    "rule": "Si la durée de conservation totale < 90 OU la durée de vie = \"J\", ET que le groupe article = \"AJ-MB CARREFOUR\" → \"CAR\" Sinon, si le secteur d'activité commence par \"10\" ou \"12\", ET qu'au moins un des canaux de distribution (cd1 à cd7) commence par \"10\" → \"CAR\" Sinon, si le secteur d'activité commence par \"10\", ET que tous les canaux de distribution (cd1 à cd7) sont égaux à \"70-RHF\" → \"ZCO\" Sinon, si le secteur d'activité commence par \"15\", ET que (OneShot ≤ 1 OU OneShot = 3), ET qu'au moins un des canaux de distribution (cd1 à cd7) est égal à \"30-EXPORT\" → \"PAL\" Sinon → \"CAR\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "ADV:Org.Commerc.1",
    "cellule": "D47",
    "lib": "OC1-unité de vente",
    "sapField": "MVKE-VRKME",
    "type": "Saisi (libre)",
    "valeur": "CAR",
    "metier": "",
    "rule": "Toujours CAR ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "ADV:Org.Comm.1",
    "cellule": "D48",
    "lib": "OC1-Groupe marchandise",
    "sapField": "MVKE-MVGR1 (5 déclinaison)",
    "type": "Liste déroulante",
    "valeur": "PF-AS-MBSA- PFinis Agen Surgel",
    "metier": "Industriel/Eclatement groupe de marchandises",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:Org.Comm.1",
    "cellule": "M48",
    "lib": "Données de taxe",
    "sapField": "MLAN-ALAND Pays / Code taxe TAXM1",
    "type": "Saisi (libre)",
    "valeur": "DE / C / Taxe réd 7%",
    "metier": "",
    "rule": "Toujours C ? Et toujours 2 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "ADV:Org.Commerc.2",
    "cellule": "D50",
    "lib": "OC2-Groupe statistique article",
    "sapField": "MVKE-VERSG",
    "type": "Liste déroulante",
    "valeur": "1-Groupe article 1",
    "metier": "SupplyChain/Groupe statistique article",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:Org.Commerc.2",
    "cellule": "K50",
    "lib": "OC2-Groupe d'article",
    "sapField": "MVKE-KONDM",
    "type": "Liste déroulante",
    "valeur": "A9-MB TRAITEUR MB",
    "metier": "SupplyChain/Groupe d'article",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:Org.Commerc.2",
    "cellule": "D51",
    "lib": "OC2-Groupe de ristournes",
    "sapField": "MVKE-KONDM",
    "type": "Saisi (libre)",
    "valeur": "A9-MB TRAITEUR MB",
    "metier": "SupplyChain/Groupe de ristournes",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:Org.Commerc.2",
    "cellule": "K51",
    "lib": "OC2-Groupe imputation article",
    "sapField": "MVKE-KTGRM",
    "type": "Liste déroulante",
    "valeur": "01-produits finis",
    "metier": "SupplyChain/Groupe imputation article",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:Org.Commerc.2",
    "cellule": "D52",
    "lib": "OC2-Article prix",
    "sapField": "MVKE-PMATN",
    "type": "Saisi (libre)",
    "valeur": "Pour OC28",
    "metier": "",
    "rule": "règle de gestion, important création d'un article 4 premier chiffre du code + 0000, statut MARA-MSTAE et sans EAN, déclencher la création d'un article prix lors de la création de code chapeau ou FL à voir c'est une copie de l'article classqiue avec les données de base et vue orgnisation commerciale",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:données gén./div",
    "cellule": "I54",
    "lib": "contrôle disponibilité",
    "sapField": "MARC-MTVFP",
    "type": "Saisi (libre)",
    "valeur": "Z3",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"Z2\" Sinon → \"Z3\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "ADV:données gén./div",
    "cellule": "I55",
    "lib": "Gestion par lots",
    "sapField": "MARA-XCHPF",
    "type": "Saisi (libre)",
    "valeur": "r",
    "metier": "?",
    "rule": "?",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "ADV:données gén./div",
    "cellule": "I57",
    "lib": "GrpeTransp",
    "sapField": "MARA-TRAGR",
    "type": "Saisi (libre)",
    "valeur": "Z001",
    "metier": "",
    "rule": "Toujours Z001 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "ADV:données gén./div",
    "cellule": "M57",
    "lib": "Grp charg",
    "sapField": "MARC-LADGR",
    "type": "Saisi (libre)",
    "valeur": "0002",
    "metier": "",
    "rule": "Si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" : Si la marque commence par \"PIC\", \"THR\" ou \"DAV\" → \"2860\" Sinon, si la marque commence par \"CDP\" → \"2861\" Sinon → \"2859\" Dans tous les autres cas → \"0002\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "ADV:données gén./div",
    "cellule": "I59",
    "lib": "Centre de profit",
    "sapField": "MARC-PRCTR",
    "type": "Liste déroulante",
    "valeur": "27PL",
    "metier": "Contrôle de gestion/Centre de profit",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "Comm.extér.:export.",
    "cellule": "J63",
    "lib": "Nomncl/N°TarifDouan",
    "sapField": "MARC-STAWN surement mais à appronfondir ?",
    "type": "Liste déroulante",
    "valeur": "19059030 = Plaques de pain:sucre et gras <5%",
    "metier": "Commerce/Nomenclature tarif douanière",
    "rule": "A vérifier dans les vues pas trouver le champs",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "Comm.extér.:export.",
    "cellule": "J64",
    "lib": "Régime douanier",
    "sapField": "???",
    "type": "Saisi (libre)",
    "valeur": "0001",
    "metier": "",
    "rule": "Toujours 0001 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Origine/Organis.Marché UE/Préférence",
    "cellule": "J66",
    "lib": "Pays d'origine",
    "sapField": "MARC-HERKL",
    "type": "Saisi (libre)",
    "valeur": "FR",
    "metier": "",
    "rule": "Toujours FR ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Origine/Organis.Marché UE/Préférence",
    "cellule": "M66",
    "lib": "Régiond'origine",
    "sapField": "MARC-HERKR (région)",
    "type": "Saisi (libre)",
    "valeur": "31",
    "metier": "",
    "rule": "Toujours 31 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Achats",
    "cellule": "J69",
    "lib": "Unité d'achat",
    "sapField": "MARA-BSTME",
    "type": "Saisi (libre)",
    "valeur": "CAR",
    "metier": "",
    "rule": "Toujours CAR ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Achats",
    "cellule": "L69",
    "lib": "UA var 1",
    "sapField": "MARA-VABME",
    "type": "Saisi (libre)",
    "valeur": "1",
    "metier": "",
    "rule": "Toujours 1 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Achats",
    "cellule": "D70",
    "lib": "Groupe d'acheteur",
    "sapField": "MARC-EKGRP",
    "type": "Saisi (libre)",
    "valeur": "INT-Groupe acheteurs Interne",
    "metier": "",
    "rule": "Si le type article est \"3A-Produit Fini:NEGOCE\" → \"NEG-Groupe acheteurs Négoce\" Sinon → \"INT-Groupe acheteurs Interne\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP1",
    "cellule": "L73",
    "lib": "Groupe de planif",
    "sapField": "MARC-DISGR",
    "type": "Saisi (libre)",
    "valeur": "Z001",
    "metier": "",
    "rule": "Si les caractères 6 et 7 de la hiérarchie produit sont différents de \"70\" → \"Z001\" Sinon → \"Z002\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP1",
    "cellule": "H75",
    "lib": "Type planification",
    "sapField": "MARC-DISMM",
    "type": "Saisi (libre)",
    "valeur": "Z5",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"PD\" Sinon → \"Z5\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP1",
    "cellule": "K75",
    "lib": "Horizon planif fixe",
    "sapField": "MARC-FXHOR",
    "type": "Saisi (libre)",
    "valeur": "5",
    "metier": "",
    "rule": "Si les 6 derniers caractères du type article sont différents de \"NEGOCE\" → 5 Sinon → 1",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP1",
    "cellule": "K76",
    "lib": "Gestionnaire",
    "sapField": "MARC-DISPO",
    "type": "Saisi (libre)",
    "valeur": "147",
    "metier": "",
    "rule": "Si l'origine (caractères 1 à 4) est : \"2802\" → \"102\" \"2833\" → \"133\" \"2847\" → \"147\" \"2886\" → \"186\" Sinon, si les caractères 17 à 20 du type article sont \"SFIN\" → \"011\" Sinon → \"120\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP1",
    "cellule": "H78",
    "lib": "Clé calc taille lot",
    "sapField": "MARC-DISLS",
    "type": "Saisi (libre)",
    "valeur": "EX",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"EX\" Sinon → les 2 premiers caractères de la clé de taille de lot division usine",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP1",
    "cellule": "K79",
    "lib": "Valeur arrondi",
    "sapField": "MARC-BSTRF",
    "type": "Saisi (libre)",
    "valeur": "1",
    "metier": "",
    "rule": "Toujours 1 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "MRP2",
    "cellule": "H82",
    "lib": "Type approvisionnemnt",
    "sapField": "MARC-BESKZ",
    "type": "Saisi (libre)",
    "valeur": "E",
    "metier": "",
    "rule": "Si les 6 derniers caractères du type article sont \"NEGOCE\" → \"F\" Sinon → \"E\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP2",
    "cellule": "N82",
    "lib": "Magasin production",
    "sapField": "MARC-LGPRO",
    "type": "Saisi (libre)",
    "valeur": "95",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"Mag.usine\" Sinon → 95",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP2",
    "cellule": "N83",
    "lib": "Magasin pour appro.ext.",
    "sapField": "MARC-LGFSB",
    "type": "Saisi (libre)",
    "valeur": "95",
    "metier": "",
    "rule": "Toujours 95 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "MRP2",
    "cellule": "H85",
    "lib": "Temps de réception",
    "sapField": "MARC-WEBAZ",
    "type": "Saisi (libre)",
    "valeur": "4",
    "metier": "Industriel/Temps de réception usine",
    "rule": "Si l'une de ces conditions est vraie : la quarantaine est vide les 6 premiers caractères du type article sont \"NEGOCE\" les caractères 17 à 20 du type article sont \"SFIN\" → vide Sinon → valeur de la cellule Temps de réception division usine",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP2",
    "cellule": "M85",
    "lib": "Délai prév livrais",
    "sapField": "MARC-PLIFZ",
    "type": "Liste déroulante",
    "valeur": "",
    "metier": "",
    "rule": "Toujours vide ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "MRP2",
    "cellule": "H86",
    "lib": "clé d'horizon",
    "sapField": "MARC-FHORI",
    "type": "Saisi (libre)",
    "valeur": "000",
    "metier": "",
    "rule": "Toujours 000 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "MRP2",
    "cellule": "M86",
    "lib": "Calendrier Planif.",
    "sapField": "MARC-MRPPP",
    "type": "Saisi (libre)",
    "valeur": "",
    "metier": "",
    "rule": "Si la clé de calcul de taille de lot est ZK alors 001 sinon vide",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP2",
    "cellule": "H89",
    "lib": "Délai de sécurité",
    "sapField": "MARC-SHZET",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "Gestion du besoin/Délai de sécurité division usine",
    "rule": "Revoir les calculs de ces champs",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "L89",
    "lib": "Dél.séc./couv.réelle",
    "sapField": "Quel champ ???",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "Gestion du besoin/Délai sec/couv réeelle usine",
    "rule": "Revoir les calculs de ces champs",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP3",
    "cellule": "D92",
    "lib": "Indicateur période",
    "sapField": "MARC-PERKZ",
    "type": "Saisi (libre)",
    "valeur": "W",
    "metier": "",
    "rule": "Toujours W ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "MRP4",
    "cellule": "J95",
    "lib": "Individuel/Collectif",
    "sapField": "MARC-SBDKZ",
    "type": "Saisi (libre)",
    "valeur": "2",
    "metier": "",
    "rule": "Toujours 2 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "MRP4",
    "cellule": "L96",
    "lib": "Fabrication répétitive",
    "sapField": "MARC-SAUFT",
    "type": "Saisi (libre)",
    "valeur": "Z006 : Agen-St Médard",
    "metier": "",
    "rule": "Si le groupe de marchandises est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → true",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP4",
    "cellule": "O96",
    "lib": "Profil fabric répét",
    "sapField": "MARC-SFEPR",
    "type": "Liste déroulante",
    "valeur": "Z006 : Agen-St Médard",
    "metier": "Industriel/Type usine",
    "rule": "Si le groupe de marchandises est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → valeur de le type d'usine",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP4",
    "cellule": "J98",
    "lib": "Unité de sortie",
    "sapField": "MARC-AUSME",
    "type": "Saisi (libre)",
    "valeur": "CAR",
    "metier": "",
    "rule": "Si le groupe de marchandises est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → CAR",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "MRP4",
    "cellule": "D99",
    "lib": "Unité de production",
    "sapField": "MARC-FRTME",
    "type": "Saisi (libre)",
    "valeur": "PAL",
    "metier": "",
    "rule": "Si le groupe de marchandises est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → PAL",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Donn.div./stockage",
    "cellule": "D102",
    "lib": "Consigne d'emballage",
    "sapField": "MARA-BEHVO",
    "type": "Saisi (libre)",
    "valeur": "01",
    "metier": "",
    "rule": "Toujours 01 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Donn.div./stockage",
    "cellule": "K102",
    "lib": "Condition de stockage",
    "sapField": "MARA-RAUBE",
    "type": "Saisi (libre)",
    "valeur": "SU",
    "metier": "",
    "rule": "Si ConditionsStockage = 1 → \"SU\" Si ConditionsStockage = 2 → \"FR\" Si ConditionsStockage = 3 → \"CP\" Sinon → \"SU\" Mais ConditionsStockage toujours à 1",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Donn.div./stockage 1",
    "cellule": "J103",
    "lib": "Durée minimale rest",
    "sapField": "MARA-MHDRZ",
    "type": "Saisi (libre)",
    "valeur": "3",
    "metier": "SupplyChain DLC/DLUO Critique",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "Donn.div./stockage 1",
    "cellule": "M103",
    "lib": "Dur conserv totale",
    "sapField": "MARA-MHDHB",
    "type": "Saisi (libre)",
    "valeur": "18",
    "metier": "Industriel/Durée de vie",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → valeur de la cellule AL22 de l'onglet \"Industriel\" Sinon → la durée de conservation totale",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Donn.div./stockage 1",
    "cellule": "J104",
    "lib": "Indic période DLC",
    "sapField": "MARA-IPRKZ",
    "type": "Saisi (libre)",
    "valeur": "M",
    "metier": "Industriel/U",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → valeur de la cellule AL22 de l'onglet \"Industriel\" Sinon → la durée de vie",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Donn.div./stockage 2",
    "cellule": "D108",
    "lib": "Unité de quantité WM",
    "sapField": "MLGN-LVSME",
    "type": "Saisi (libre)",
    "valeur": "CAR",
    "metier": "",
    "rule": "Si le groupe de marchandises de l'onglet Saisie est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → CAR",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Donn.div./stockage 2",
    "cellule": "D109",
    "lib": "UQ défaut fiche art",
    "sapField": "MLGN-VOMEM",
    "type": "Saisi (libre)",
    "valeur": "M",
    "metier": "",
    "rule": "Si le groupe de marchandises de l'onglet Saisie est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → M",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Donn.div./stockage",
    "cellule": "H110",
    "lib": "Type magasin EM",
    "sapField": "MLGN-LTKZE",
    "type": "Calculé (auto)",
    "valeur": "003",
    "metier": "Industriel/Type magasin EM",
    "rule": "Si le groupe de marchandises de l'onglet Saisie est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → (Si l'origine est \"2847-Agen2\" ET la hauteur palette ≤ 1500 → \"002\" Si l'origine est \"2847-Agen2\" ET la hauteur palette > 1500 → \"003\" Sinon → \"001\")",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "Donn.div./stockage 2",
    "cellule": "K111",
    "lib": "Entrée add autorisée",
    "sapField": "MLGN-KZZUL",
    "type": "Saisi (libre)",
    "valeur": "",
    "metier": "",
    "rule": "Si le groupe de marchandises de l'onglet Saisie est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → true",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Gestion empl.mag.2",
    "cellule": "D114",
    "lib": "Qté moy.chg",
    "sapField": "LHMG1 MLGN à revoir enseù",
    "type": "Saisi (libre)",
    "valeur": "48",
    "metier": "Industriel/Nbr d'uc Palette",
    "rule": "Si le groupe de marchandises de l'onglet Saisie est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → Nbr d'UC/Palette",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Gestion empl.mag.2",
    "cellule": "F114",
    "lib": "UQ (unité)",
    "sapField": "MLGN à revoir LHME1",
    "type": "Saisi (libre)",
    "valeur": "CAR",
    "metier": "",
    "rule": "Si le groupe de marchandises de l'onglet Saisie est vide → vide Sinon, si le groupe de marchandises commence par \"PF-H\" ET que la facturation est \"TDL\" → vide Sinon → CAR",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Gestion empl.mag.2",
    "cellule": "G114",
    "lib": "TUS (type unité stockage)",
    "sapField": "MLGN à revoir LETY1",
    "type": "Saisi (libre)",
    "valeur": "Z81 :palette 80x120",
    "metier": "Industriel/Type palette",
    "rule": "Si le 4ème caractère du type palette est \"8\" → \"Z81 :palette 80x120\" Sinon → \"Z82 :palette 100x120\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "Comptabilité 1",
    "cellule": "D119",
    "lib": "Classe valorisation",
    "sapField": "MBEW-BKLAS",
    "type": "Saisi (libre)",
    "valeur": "7012 produits finis",
    "metier": "",
    "rule": "Si le type article se termine par \"NEGOCE\" ET la hiérarchie produit commence par \"27\" → \"2038 négoce traiteur\" Si le type article se termine par \"NEGOCE\" ET la hiérarchie produit commence par \"21\" → \"2027 Crèmes Glacées\" Si le type article se termine par \"NEGOCE\" ET la hiérarchie produit commence par \"22\" → \"2030 négoce pâtisserie\" Si les caractères 17 à 20 du type article sont \"SFIN\" → \"4022 pr.semi-finis\" Sinon → \"7012 produits finis\"",
    "cat": "REGLE",
    "status": "regle_reusable"
  },
  {
    "section": "Comptabilité 1",
    "cellule": "I119",
    "lib": "uniité de prix",
    "sapField": "MBEW-PEINH",
    "type": "Saisi (libre)",
    "valeur": "1000",
    "metier": "",
    "rule": "Toujours 1000 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Comptabilité 1",
    "cellule": "D120",
    "lib": "Code prix",
    "sapField": "MBEW-VPRSV",
    "type": "Saisi (libre)",
    "valeur": "S",
    "metier": "",
    "rule": "Toujours S ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Comptabilité 1",
    "cellule": "I120",
    "lib": "Prix standard",
    "sapField": "MBEW-STPRS",
    "type": "Saisi (libre)",
    "valeur": "1",
    "metier": "",
    "rule": "Toujours 1 ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "CCR 1",
    "cellule": "G125",
    "lib": "Avec struct de qtés",
    "sapField": "MBEW-EKALR",
    "type": "Saisi (libre)",
    "valeur": "",
    "metier": "",
    "rule": "Toujours true ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "CCR 1",
    "cellule": "G126",
    "lib": "Origine article",
    "sapField": "MBEW-HKMAT",
    "type": "Saisi (libre)",
    "valeur": "",
    "metier": "",
    "rule": "Toujours true ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "CCR 1",
    "cellule": "D127",
    "lib": "Groupe de frais généraux",
    "sapField": "MBEW-KOSGR",
    "type": "Saisi (libre)",
    "valeur": "FG",
    "metier": "",
    "rule": "Si les 6 derniers caractères du type article sont \"NEGOCE\" → \"NEGO\" Sinon → \"FG\"",
    "cat": "REGLE",
    "status": "regle_todo"
  },
  {
    "section": "CLASSIFICATION 023",
    "cellule": "L133",
    "lib": "023-LOBM-2USTD (statut utilisation lot)",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "",
    "metier": "",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 023",
    "cellule": "L134",
    "lib": "023-LOBM-VFDAT (DLC lot)",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "",
    "metier": "",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 023",
    "cellule": "L135",
    "lib": "023-LOBM-RLZ (durée vie résiduelle)",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "",
    "metier": "",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L138",
    "lib": "NBRE DE JOURS DE STOCKAGE",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "2",
    "metier": "",
    "rule": "Toujours 2 ?",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L139",
    "lib": "DIVISION PRINCIPALE STOCKAGE",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "1 (VRAI)",
    "metier": "",
    "rule": "Toujours vrai ?",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L140",
    "lib": "POURCENTAGE DE COLIS",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "1 (VRAI)",
    "metier": "",
    "rule": "Toujours vrai ?",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L141",
    "lib": "MARQUE INDUSTRIELLE MBSA",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "1 (VRAI)",
    "metier": "",
    "rule": "Toujours vrai ?",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L142",
    "lib": "CLASSE ABCD BSA",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "0",
    "metier": "",
    "rule": "Toujours 0 ?",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "K143",
    "lib": "FORMAT DATE ETIQ COLIS (MBSA ATELIER)",
    "sapField": "Caract. AUSP",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "Industriel/Format date Etiq Colis",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "K144",
    "lib": "MASQUE ETIQUETTE COLIS (MBSA LIGNE)",
    "sapField": "Caract. AUSP",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "Industriel/Masque étiquette colis",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "K145",
    "lib": "DESIGNATION CLIENT SUR COLIS (MBSA FORMAT PRODUIT)",
    "sapField": "Caract. AUSP",
    "type": "Saisi (libre)",
    "valeur": "4 LOTS DE 5 PLAQUES PANACHEES",
    "metier": "Industriel/Designation client s/colis",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "K146",
    "lib": "FORMAT DLUO ETIQ COLIS (MBSA SERIE PRODUIT)",
    "sapField": "Caract. AUSP",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "Industriel/Format DLUO Etiq colis",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "K148",
    "lib": "MBSA MARQUE LOGISTIQUE",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "BSA-BONCOLAC FS",
    "metier": "Industriel/Profil de couverture",
    "rule": "4 premiers chiffres",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L149",
    "lib": "MBSA MASQUE STANDARD Niv. Art.",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "",
    "metier": "Commerce/Marque",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "L150",
    "lib": "MBSA MASQUE SPECIFIQUE Niv.Art",
    "sapField": "Caract. AUSP",
    "type": "Calculé (auto)",
    "valeur": "",
    "metier": "",
    "rule": "Si le produit bio = 1 ET la marque ne commence pas par \"U00\" → \"STANDARDDLUO-BIO.LAB\" Si le produit bio = 1 ET la marque commence par \"U00\" → \"STANDARDDLUO-U-BIO.LAB\" Sinon → vide Mais produit bio est toujours à 2",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "CLASSIFICATION 001",
    "cellule": "M150",
    "lib": "MBSA TYPE DE SUPPORT",
    "sapField": "Caract. AUSP",
    "type": "Liste déroulante",
    "valeur": "SME80 (Palette 80x120 Eu)",
    "metier": "",
    "rule": "Si NomEtiquette est renseigné → la valeur de NomEtiquette Sinon, si le produit est bio → \"NONSTDDLUO-BIO.LAB\" Sinon → vide Mais NomEtiquette est toujours vide ??",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "001 CLASSE ARTICLE",
    "cellule": "L151",
    "lib": "MBSA TYPE DE SUPPORT",
    "sapField": "Classif. (custom)",
    "type": "Liste déroulante",
    "valeur": "SME80",
    "metier": "",
    "rule": "5 premiers caractères de type de palette",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "Consigne emballage std (POP)",
    "cellule": "K160",
    "lib": "Prof contrôle / génération code",
    "sapField": "Profil contrôle POP",
    "type": "Saisi (libre)",
    "valeur": "Z1",
    "metier": "",
    "rule": "Toujours Z1 ??",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Consigne emballage std (POP)",
    "cellule": "G161",
    "lib": "Consigne emballage",
    "sapField": "Consigne embal. (HU)",
    "type": "Calculé (auto)",
    "valeur": "P419805",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"P\" suivi de la valeur de la cellule AP20 de l'onglet \"Industriel\" (qui est vide) Sinon → \"P\" suivi des valeurs de code article et VL",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "Consigne emballage std (POP)",
    "cellule": "J161",
    "lib": "Désignation",
    "sapField": "Consigne embal.",
    "type": "Calculé (auto)",
    "valeur": "419805 Palette / SME80 : Palette 80x120 Europe",
    "metier": "",
    "rule": "Les caractères 1 à 4 du code article, concaténés avec la valeur de la FL puis \"Fictif\" puis type de palette",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "Consigne emballage std (POP)",
    "cellule": "G163",
    "lib": "Poste P — composant",
    "sapField": "Consigne (poste)",
    "type": "Saisi (libre)",
    "valeur": "Type P / SME80 : Palette 80x120 Europe (qté 1)",
    "metier": "",
    "rule": "Toujours P ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Consigne emballage std (POP)",
    "cellule": "G164",
    "lib": "Poste M — article",
    "sapField": "Consigne (poste)",
    "type": "Saisi (libre)",
    "valeur": "Type M / 419805 — qté 48 / 0.01 / CAR",
    "metier": "",
    "rule": "Toujours M ?",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "Consigne emballage fictif (POP)",
    "cellule": "K168",
    "lib": "Prof contrôle / génération code",
    "sapField": "Profil contrôle POP",
    "type": "Saisi (libre)",
    "valeur": "Z1",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "Consigne emballage fictif (POP)",
    "cellule": "G169",
    "lib": "Consigne emballage",
    "sapField": "Consigne embal. fictive",
    "type": "Calculé (auto)",
    "valeur": "F419805",
    "metier": "",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "Consigne emballage fictif (POP)",
    "cellule": "J169",
    "lib": "Désignation",
    "sapField": "Consigne embal.",
    "type": "Calculé (auto)",
    "valeur": "419805 Fictif",
    "metier": "",
    "rule": "",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "Consigne emballage fictif (POP)",
    "cellule": "G171",
    "lib": "Poste P — composant",
    "sapField": "Consigne (poste)",
    "type": "Saisi (libre)",
    "valeur": "SMFictif80 (qté 1 / PI)",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "Consigne emballage fictif (POP)",
    "cellule": "G172",
    "lib": "Poste M — article",
    "sapField": "Consigne (poste)",
    "type": "Saisi (libre)",
    "valeur": "419805 — qté 47.99 / 0.01 / CAR",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "POF 1",
    "cellule": "G176",
    "lib": "Type de recherche",
    "sapField": "Détermination POF",
    "type": "Saisi (libre)",
    "valeur": "CE",
    "metier": "",
    "rule": "Toujours CE",
    "cat": "CONSTANTE",
    "status": "constante"
  },
  {
    "section": "POF 1",
    "cellule": "D178",
    "lib": "Article",
    "sapField": "MATNR",
    "type": "Calculé (auto)",
    "valeur": "419805",
    "metier": "",
    "rule": "Code article + VL",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "POF 1",
    "cellule": "F178",
    "lib": "Consigne d'emballage",
    "sapField": "Consigne embal.",
    "type": "Calculé (auto)",
    "valeur": "P419805",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"P\" suivi de la valeur de la cellule AP20 de l'onglet \"Industriel\" (qui est vide) Sinon → \"P\" suivi des valeurs de code article et VL",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "POF 1",
    "cellule": "I178",
    "lib": "Consigne emb.alt 1",
    "sapField": "Consigne embal. fictive",
    "type": "Calculé (auto)",
    "valeur": "F419805",
    "metier": "",
    "rule": "Si les caractères 17 à 20 du type article sont \"SFIN\" → \"F\" suivi de la valeur de la cellule AP20 de l'onglet \"Industriel\" (qui est vide) Sinon → \"F\" suivi des valeurs de code article et VL",
    "cat": "CALCUL",
    "status": "calcul"
  },
  {
    "section": "Workflow validation",
    "cellule": "D184",
    "lib": "Emetteur Fiche de Lancement",
    "sapField": "Workflow (custom)",
    "type": "Saisi (libre)",
    "valeur": "TIERSOONE Romain (371301)",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "F184",
    "lib": "Date fiche de lancement",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "27/08/2019",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "H184",
    "lib": "Date de mise à disposition",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "29/08/2019",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "I184",
    "lib": "Emetteur commerce",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "L50104",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "J184",
    "lib": "Emetteur industriel",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "L55026",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "K184",
    "lib": "Emetteur Gestion du besoin",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "L59815",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "L184",
    "lib": "Emetteur Supply Chain",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "L59815",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "M184",
    "lib": "Emetteur Contrôle de Gestion",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "L59815",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "N184",
    "lib": "Date Visa commerce",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "19/11/2025",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "O184",
    "lib": "Date Visa industriel",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "18/11/2025",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "P184",
    "lib": "Date Visa Gestion du besoin",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "29/10/2025",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "Q184",
    "lib": "Date Visa Supply Chain",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "29/10/2025",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "R184",
    "lib": "Date Visa Contrôle de Gestion",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "29/10/2025",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "S184",
    "lib": "Date Maxi Création SAP",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "14/08/2019",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "T184",
    "lib": "DeadLine complète",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "19/08/2019",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "Workflow validation",
    "cellule": "U184",
    "lib": "Date Retour fiche de lancement",
    "sapField": "Workflow",
    "type": "Saisi (libre)",
    "valeur": "13/08/2019",
    "metier": "",
    "rule": "",
    "cat": "WORKFLOW",
    "status": "workflow"
  },
  {
    "section": "MRP1",
    "cellule": "F192",
    "lib": "Type planification",
    "sapField": "MARC-DISMM",
    "type": "Saisi (libre)",
    "valeur": "Z5",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP1",
    "cellule": "K192",
    "lib": "Horizon planif fixe",
    "sapField": "MARC-FXHOR",
    "type": "Saisi (libre)",
    "valeur": "1",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP1",
    "cellule": "N192",
    "lib": "Méthode lotissement",
    "sapField": "MARC-DISLS",
    "type": "Saisi (libre)",
    "valeur": "ZN",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "F193",
    "lib": "Type appro",
    "sapField": "MARC-BESKZ",
    "type": "Saisi (libre)",
    "valeur": "F",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "F195",
    "lib": "Appro spécial",
    "sapField": "MARC-SOBSL",
    "type": "Saisi (libre)",
    "valeur": "43-AGEN",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "F196",
    "lib": "Magasin production",
    "sapField": "MARC-LGPRO",
    "type": "Saisi (libre)",
    "valeur": "95 (barré)",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "M196",
    "lib": "Sites de stockage (défaut)",
    "sapField": "?? à revoir surement la division",
    "type": "Liste déroulante",
    "valeur": "2820 / 2824",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "F197",
    "lib": "Mag pour appro.ext",
    "sapField": "MARC-LGFSB",
    "type": "Saisi (libre)",
    "valeur": "95",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "L197",
    "lib": "Délai prévisionnel de livraison",
    "sapField": "MARC-PLIFZ",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "F198",
    "lib": "Temps de réception",
    "sapField": "MARC-WEBAZ",
    "type": "Saisi (libre)",
    "valeur": "0",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "K199",
    "lib": "Profil de couverture",
    "sapField": "MARC-RWPRO",
    "type": "Saisi (libre)",
    "valeur": "",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "K201",
    "lib": "Délai de sécurité",
    "sapField": "MARC-SHZET",
    "type": "Saisi (libre)",
    "valeur": "2",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MRP2",
    "cellule": "N201",
    "lib": "Dél.séc./couv.réelle",
    "sapField": "MARC-SHFLG ? ?",
    "type": "Saisi (libre)",
    "valeur": "21",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "CCR1",
    "cellule": "F203",
    "lib": "Groupe de frais gén.",
    "sapField": "MARC (overhead)",
    "type": "Saisi (libre)",
    "valeur": "FG (barré)",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MMSC",
    "cellule": "E207",
    "lib": "Domaine MMSC — Agen2 / BA",
    "sapField": "MARD-LGORT",
    "type": "Saisi (libre)",
    "valeur": "2847-Agen2 / BA",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MMSC",
    "cellule": "E208",
    "lib": "Domaine MMSC — Agen2 / NC",
    "sapField": "MARD-LGORT",
    "type": "Saisi (libre)",
    "valeur": "2847-Agen2 / NC",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  },
  {
    "section": "MMSC",
    "cellule": "E209",
    "lib": "Domaine MMSC — Agen2 / EMB",
    "sapField": "MARD-LGORT",
    "type": "Saisi (libre)",
    "valeur": "2847-Agen2 / EMB",
    "metier": "",
    "rule": "",
    "cat": "SAISIE",
    "status": "saisie"
  }
];

// Métadonnées d'affichage par nature (libellé + classes Tailwind du badge).
export const NATURE_META = {
  SAISIE:    { label: 'Saisie',    badge: 'bg-emerald-100 text-emerald-800' },
  CONSTANTE: { label: 'Constante', badge: 'bg-slate-100 text-slate-600' },
  REGLE:     { label: 'Règle',     badge: 'bg-amber-100 text-amber-800' },
  CALCUL:    { label: 'Calcul',    badge: 'bg-violet-100 text-violet-800' },
  WORKFLOW:  { label: 'Workflow',  badge: 'bg-rose-100 text-rose-800' },
};

// Métadonnées d'affichage par statut de règle.
export const STATUS_META = {
  saisie:         { label: 'Saisie',        badge: 'bg-emerald-50 text-emerald-700 ring-1 ring-emerald-200' },
  constante:      { label: 'Constante',     badge: 'bg-slate-50 text-slate-600 ring-1 ring-slate-200' },
  calcul:         { label: 'Calcul',        badge: 'bg-violet-50 text-violet-700 ring-1 ring-violet-200' },
  workflow:       { label: 'Hors SAP',      badge: 'bg-rose-50 text-rose-700 ring-1 ring-rose-200' },
  regle_reusable: { label: 'Règle · on a',  badge: 'bg-sky-50 text-sky-700 ring-1 ring-sky-200' },
  regle_todo:     { label: 'Règle · à coder', badge: 'bg-orange-50 text-orange-700 ring-1 ring-orange-200' },
};

// Regroupe les champs par vue SAP (section), en préservant l'ordre d'apparition.
export function groupBySection(fields = FL_FIELDS) {
  const map = new Map();
  for (const f of fields) {
    if (!map.has(f.section)) map.set(f.section, []);
    map.get(f.section).push(f);
  }
  return [...map.entries()].map(([section, items]) => ({ section, items }));
}

// Compte par nature (cat).
export function counts(fields = FL_FIELDS) {
  const c = { SAISIE: 0, CONSTANTE: 0, REGLE: 0, CALCUL: 0, WORKFLOW: 0 };
  for (const f of fields) c[f.cat] = (c[f.cat] || 0) + 1;
  return c;
}

// Compte des règles : réutilisables (on a) vs à coder (il nous faut).
export function ruleCounts(fields = FL_FIELDS) {
  let reusable = 0, todo = 0;
  for (const f of fields) {
    if (f.status === 'regle_reusable') reusable += 1;
    else if (f.status === 'regle_todo') todo += 1;
  }
  return { reusable, todo, total: reusable + todo };
}
